# Generated by Django 3.0.2 on 2020-03-17 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('is_admin', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Valuable',
            fields=[
                ('name', models.CharField(max_length=1024)),
                ('price', models.FloatField()),
                ('stock', models.IntegerField(default=0)),
                ('serial', models.UUIDField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('amount', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('P', 'Purchase'), ('S', 'Sale')], max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='InventoryAndSalesManagementSystemApp.User')),
                ('valuable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='InventoryAndSalesManagementSystemApp.Valuable')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('valuable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='InventoryAndSalesManagementSystemApp.Valuable')),
            ],
        ),
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('valuable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='InventoryAndSalesManagementSystemApp.Valuable')),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('VCR', 'Valuable Created'), ('VDE', 'Valuable Deleted'), ('VST', 'Valuable Stocked'), ('VRE', 'Valuable Renamed'), ('VPC', 'Valuable Price Changed'), ('VSO', 'Valuable Sold')], max_length=3)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='InventoryAndSalesManagementSystemApp.User')),
            ],
        ),
    ]
